-- MySQL Script generated by MySQL Workbench
-- 03/10/16 00:17:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wedding
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wedding` ;

-- -----------------------------------------------------
-- Schema wedding
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wedding` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `wedding` ;

-- -----------------------------------------------------
-- Table `wedding`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(200) NULL,
  `full_name` VARCHAR(200) NULL,
  `birthday` INT(11) NULL,
  `phone` DOUBLE NULL,
  `is_official` TINYINT(1) NULL DEFAULT 0,
  `is_disable` TINYINT(1) NULL DEFAULT 0,
  `is_delete` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedding`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(200) NULL,
  `password_hash` TEXT NULL,
  `auth_key` VARCHAR(500) NULL,
  `status` INT(2) NULL DEFAULT 10,
  `employee_id` INT NULL,
  `is_admin` TINYINT(1) NULL DEFAULT 0,
  `token` VARCHAR(45) NULL,
  `expired_date` INT(11) NULL,
  `created_date` INT(11) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `wedding`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_employee_idx` ON `wedding`.`user` (`employee_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `wedding`.`employee`
-- -----------------------------------------------------
START TRANSACTION;
USE `wedding`;
INSERT INTO `wedding`.`employee` (`id`, `code`, `full_name`, `birthday`, `phone`, `is_official`, `is_disable`, `is_delete`) VALUES (1, '123', 'bao', NULL, NULL, 0, 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `wedding`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `wedding`;
INSERT INTO `wedding`.`user` (`id`, `user_name`, `password_hash`, `auth_key`, `status`, `employee_id`, `is_admin`, `token`, `expired_date`, `created_date`) VALUES (1, 'admin', '$2y$13$kN0mQgtwVDRktJBK5N7fPuKTO8kwLfJlrda0KHbeXDJxExwzwHf1.', '17Mto0DdMLwW5j62vGl1d_gZP_mUGw8i', 10, NULL, 1, NULL, NULL, NULL);
INSERT INTO `wedding`.`user` (`id`, `user_name`, `password_hash`, `auth_key`, `status`, `employee_id`, `is_admin`, `token`, `expired_date`, `created_date`) VALUES (2, 'bao.lam', '$2y$13$kN0mQgtwVDRktJBK5N7fPuKTO8kwLfJlrda0KHbeXDJxExwzwHf1.', '17Mto0DdMLwW5j62vGl1d_gZP_mUGw8i', 10, 1, 0, NULL, NULL, NULL);

COMMIT;

